Repository UberBarber/UberBarber, pull requests merged in 2023-01, with the labels that each got.

#10 Hotfix/add gitignore file
  .gitignore
  CODEOWNERS
Labels: hotfix

#11 Improvement/create project
  UberBarber/UberBarber.sln
  UberBarber/UberBarber/App.xaml
  UberBarber/UberBarber/App.xaml.cs
  UberBarber/UberBarber/AssemblyInfo.cs
  UberBarber/UberBarber/MainWindow.xaml
  UberBarber/UberBarber/MainWindow.xaml.cs
  UberBarber/UberBarber/UberBarber.csproj
Labels: development

#12 Improvement/create class with database connection
  UberBarber/UberBarber.sln
  UberBarber/UberBarber/DbConnection.cs
  UberBarber/UberBarber/MainWindow.xaml.cs
  UberBarber/UberBarber/UberBarber.csproj
Labels: development

#14 Create Log In UI
  UberBarber/UberBarber/App.xaml
  UberBarber/UberBarber/Images/back-images.jpg
  UberBarber/UberBarber/Images/key-icon.png
  UberBarber/UberBarber/Images/logoo.png
  UberBarber/UberBarber/Images/user-icon.png
  UberBarber/UberBarber/UberBarber.csproj
  UberBarber/UberBarber/View/LoginView.xaml
  UberBarber/UberBarber/View/LoginView.xaml.cs
Labels: enhancement

#19 Improvement/Front end- User registration
  UberBarber/UberBarber/Images/emaill.png
  UberBarber/UberBarber/UberBarber.csproj
  UberBarber/UberBarber/View/MainWindow.xaml
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/View/User.xaml
  UberBarber/UberBarber/View/User.xaml.cs
Labels: enhancement
