Repository UberBarber/UberBarber, pull requests merged in 2023-02, with the labels that each got.

#23 Improvement/add users
  UberBarber/UberBarber/User/User.cs
  UberBarber/UberBarber/View/LoginView.xaml
  UberBarber/UberBarber/View/LoginView.xaml.cs
  UberBarber/UberBarber/View/MainWindow.xaml
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/View/User.xaml.cs
  UberBarber/UberBarber/View/UserRegistration.xaml
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
  UberBarber/UberBarber/database/DbConnection.cs
Labels: development

#30 Improvement/g UI main window
  UberBarber/UberBarber/App.xaml
  UberBarber/UberBarber/Images/profile-picture.png
  UberBarber/UberBarber/Styles/ButtonStyles.xaml
  UberBarber/UberBarber/Styles/UIColors.xaml
  UberBarber/UberBarber/UberBarber.csproj
  UberBarber/UberBarber/View/LoginView.xaml
  UberBarber/UberBarber/View/MainWindow.xaml
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/View/UserRegistration.xaml
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
Labels: development, WPF, .cs

#33 Task/uber barber#24 mesage labels
  UberBarber/UberBarber/View/LoginView.xaml
  UberBarber/UberBarber/View/LoginView.xaml.cs
  UberBarber/UberBarber/View/UserRegistration.xaml
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
  UberBarber/UberBarber/database/DbConnection.cs
Labels: enhancement, WPF, .cs

#36 Tasks/uber barber #29 #28 #25 user validation
  UberBarber/UberBarber/View/LoginView.xaml
  UberBarber/UberBarber/View/LoginView.xaml.cs
  UberBarber/UberBarber/View/UserRegistration.xaml
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
Labels: enhancement, WPF, .cs

#37 Task/uber barber#20 user handling
  UberBarber/UberBarber/User/User.cs
  UberBarber/UberBarber/View/LoginView.xaml.cs
  UberBarber/UberBarber/View/MainWindow.xaml
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
  UberBarber/UberBarber/database/DbConnection.cs
Labels: enhancement, WPF, .cs

#39 Task/uber barber#35 get logged user
  UberBarber/UberBarber/User/CurrentUser.cs
  UberBarber/UberBarber/View/LoginView.xaml.cs
  UberBarber/UberBarber/View/MainWindow.xaml
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
Labels: development, WPF, MySQL, .cs

#40 Task/uber barber#38 main window UI
  UberBarber/UberBarber/App.xaml
  UberBarber/UberBarber/Styles/ButtonStyles.xaml
  UberBarber/UberBarber/Styles/GridStyle.xaml
  UberBarber/UberBarber/Styles/UIColors.xaml
  UberBarber/UberBarber/UberBarber.csproj
  UberBarber/UberBarber/View/LoginView.xaml
  UberBarber/UberBarber/View/MainWindow.xaml
Labels: WPF, .cs

#41 Improvement/send email fix code
  UberBarber/UberBarber/Styles/GridStyle.xaml
  UberBarber/UberBarber/User/MailSender.cs
  UberBarber/UberBarber/View/UserRegistration.xaml
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
Labels: enhancement, MySQL, .cs

#43 add is_worker boolean to EditUser method, check checkbox permissions …
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
Labels: hotfix

#44 add email validation
  UberBarber/UberBarber/User/MailSender.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
Labels: enhancement

#46 Task/uber barber#34 barber handling
  UberBarber/UberBarber/Barber/Barber.cs
  UberBarber/UberBarber/Service/Service.cs
  UberBarber/UberBarber/User/User.cs
  UberBarber/UberBarber/View/AddOrDeleteServiceOfBarber.xaml
  UberBarber/UberBarber/View/AddOrDeleteServiceOfBarber.xaml.cs
  UberBarber/UberBarber/View/BarberEditWindow.xaml
  UberBarber/UberBarber/View/BarberEditWindow.xaml.cs
  UberBarber/UberBarber/View/MainWindow.xaml
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/View/ServiceWindow.xaml
  UberBarber/UberBarber/View/ServiceWindow.xaml.cs
  UberBarber/UberBarber/database/BarberQueries/BarberQueries.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
  UberBarber/UberBarber/database/ServiceQueries/ServiceQueries.cs
Labels: enhancement, development, MySQL, .cs

#45 Improvement/create appointments handling functionality
  UberBarber/UberBarber/Appointments/Appointments.cs
  UberBarber/UberBarber/Customer/Customer.cs
  UberBarber/UberBarber/Styles/ButtonStyles.xaml
  UberBarber/UberBarber/User/CurrentUser.cs
  UberBarber/UberBarber/View/AddAppointment.xaml
  UberBarber/UberBarber/View/AddAppointment.xaml.cs
  UberBarber/UberBarber/View/LoginView.xaml.cs
  UberBarber/UberBarber/View/MainWindow.xaml
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/AppointmentQueries/AppointmentQueries.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
  UberBarber/UberBarber/database/DbConnection.cs
Labels: enhancement, development, WPF, MySQL, .cs

#47 move user queries to separeted directory
  UberBarber/UberBarber/View/BarberEditWindow.xaml.cs
  UberBarber/UberBarber/View/LoginView.xaml.cs
  UberBarber/UberBarber/View/MainWindow.xaml.cs
  UberBarber/UberBarber/View/UserRegistration.xaml.cs
  UberBarber/UberBarber/database/DatabaseQueries.cs
  UberBarber/UberBarber/database/UserQueries/UserQueries.cs
Labels: hotfix, .cs
